// generated by Neptune Namespaces v4.x.x
// file: Prime.Escape/Client/index.js

(module.exports = require('./namespace'))

.addModules({
  Main:           require('./Main'),
  StandardImport: require('./StandardImport')
});
require('./Components');
require('./Models');