# generated by Neptune Namespaces v3.x.x
# file: Prime.Climb/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  StandardImport: require './StandardImport'
require './Client'