# generated by Neptune Namespaces v3.x.x
# file: Prime.Climb/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Prime.Climb', class Climb extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Client/namespace'