// generated by Neptune Namespaces v4.x.x
// file: Prime.Escape/index.js

(module.exports = require('./namespace'))

.addModules({
  StandardImport: require('./StandardImport')
});
require('./Client');
require('./Data');
require('./Styles');