// generated by Neptune Namespaces v4.x.x
// file: Prime.Escape/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Prime.Escape',
  (class Escape extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Client/namespace');
require('./Data/namespace');
require('./Styles/namespace');