# generated by Neptune Namespaces v3.x.x
# file: Prime.Escape/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Prime.Escape', class Escape extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Client/namespace';
require './Data/namespace';
require './Styles/namespace'