# generated by Neptune Namespaces v3.x.x
# file: Prime.Climb/Client/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Board:           require './Board'          
  Constants:       require './Constants'      
  Lib:             require './Lib'            
  Main:            require './Main'           
  Number:          require './Number'         
  Pawn:            require './Pawn'           
  PawnTurnOptions: require './PawnTurnOptions'
  Root:            require './Root'           
  StandardImport:  require './StandardImport' 
  TurnOption:      require './TurnOption'     
require './Models'