# generated by Neptune Namespaces v3.x.x
# file: Prime.Climb/Client/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Board:           require './Board'          
  Board2:          require './Board2'         
  Constants:       require './Constants'      
  Game:            require './Game'           
  Game2:           require './Game2'          
  Lib:             require './Lib'            
  Main:            require './Main'           
  Number:          require './Number'         
  Pawn:            require './Pawn'           
  PawnTurnOptions: require './PawnTurnOptions'
  StandardImport:  require './StandardImport' 
  TurnOption:      require './TurnOption'     
require './Models'