// generated by Neptune Namespaces v4.x.x
// file: Prime.Escape/Client/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  Board:  require('./Board'),
  Game:   require('./Game'),
  Number: require('./Number'),
  Pawn:   require('./Pawn')
});