# generated by Neptune Namespaces v3.x.x
# file: Prime.Escape/Client/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Board:  require './Board' 
  Game:   require './Game'  
  Number: require './Number'
  Pawn:   require './Pawn'  