// generated by Neptune Namespaces v4.x.x
// file: Prime.Escape/Styles/namespace.js

module.exports = require('../namespace').addNamespace(
  'Styles',
  class Styles extends Neptune.PackageNamespace {}
);
