# generated by Neptune Namespaces v3.x.x
# file: Prime.Game/Client/Components/Partials/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  GameHeader: require './GameHeader'