// generated by Neptune Namespaces v4.x.x
// file: Prime.Game/Client/Components/Partials/namespace.js

module.exports = require('../namespace').addNamespace(
  'Partials',
  class Partials extends Neptune.PackageNamespace {}
);
