# generated by Neptune Namespaces v3.x.x
# file: tests/Prime.Climb/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Prime.Climb', class Climb extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
