// generated by Neptune Namespaces v4.x.x
// file: Prime.Game/Client/index.js

(module.exports = require('./namespace'))

.addModules({
  Board:           require('./Board'),
  Constants:       require('./Constants'),
  Game:            require('./Game'),
  Lib:             require('./Lib'),
  Main:            require('./Main'),
  Number:          require('./Number'),
  Pawn:            require('./Pawn'),
  PawnTurnOptions: require('./PawnTurnOptions'),
  StandardImport:  require('./StandardImport'),
  TurnOption:      require('./TurnOption')
});
require('./Components');
require('./Models');
require('./Styles');