# generated by Neptune Namespaces v3.x.x
# file: Prime.Game/Client/namespace.coffee

module.exports = (require '../namespace').addNamespace('Client', class Client extends Neptune.PackageNamespace)
require './Components/namespace';
require './Models/namespace';
require './Styles/namespace'