// generated by Neptune Namespaces v4.x.x
// file: Prime.Game/Client/namespace.js

module.exports = require('../namespace').addNamespace(
  'Client',
  class Client extends Neptune.PackageNamespace {}
);
require('./Components/namespace');
require('./Models/namespace');
require('./Styles/namespace');