// generated by Neptune Namespaces v4.x.x
// file: Prime.Game/Client/Components/namespace.js

module.exports = module.exports =  require('../namespace').vivifySubnamespace('Components');
require('./Partials/namespace');