# generated by Neptune Namespaces v3.x.x
# file: Prime.Climb/Client/Components/namespace.coffee

module.exports = (require '../namespace').vivifySubnamespace 'Components'
require './Partials/namespace'