# generated by Neptune Namespaces v3.x.x
# file: Prime.Climb/Client/Styles/namespace.coffee

module.exports = (require '../namespace').addNamespace('Styles', class Styles extends Neptune.PackageNamespace)
