# generated by Neptune Namespaces v3.x.x
# file: Prime.Game/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Prime.Game', class Game extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Client/namespace'