// generated by Neptune Namespaces v4.x.x
// file: Prime.Game/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Prime.Game',
  (class Game extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Client/namespace');