# generated by Neptune Namespaces v3.x.x
# file: Prime.Game/Client/Styles/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  GameStyles: require './GameStyles'
  TextStyles: require './TextStyles'