// generated by Neptune Namespaces v4.x.x
// file: Prime.Game/Client/Styles/index.js

(module.exports = require('./namespace'))

.addModules({
  GameStyles: require('./GameStyles'),
  TextStyles: require('./TextStyles')
});