// generated by Neptune Namespaces v4.x.x
// file: Prime.Escape/Client/Models/index.js

(module.exports = require('./namespace'))

.addModules({
  CurrentGame: require('./CurrentGame'),
  Highlights:  require('./Highlights')
});