# generated by Neptune Namespaces v3.x.x
# file: Prime.Escape/Client/Models/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CurrentGame: require './CurrentGame'
  Highlights:  require './Highlights' 