// generated by Neptune Namespaces v4.x.x
// file: Prime.Escape/Client/Models/namespace.js

module.exports = require('../namespace').addNamespace(
  'Models',
  class Models extends Neptune.PackageNamespace {}
);
