# generated by Neptune Namespaces v3.x.x
# file: Prime.Climb/Client/Components/Partials/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  GameHeader: require './GameHeader'